using System;

namespace gaudio.effect
{
    public enum GDriverCode
    {
        AUDIO_ATTENUATION_MIN = 0,
        AUDIO_ATTENUATION_INVERSE_DISTANCE = AUDIO_ATTENUATION_MIN,
        AUDIO_ATTENUATION_INVERSE_DISTANCE_CLAMPED,
        AUDIO_ATTENUATION_LINEAR_DISTANCE,
        AUDIO_ATTENUATION_LINEAR_DISTANCE_CLAMPED,
        AUDIO_ATTENUATION_EXPONENT_DISTANCE,
        AUDIO_ATTENUATION_EXPONENT_DISTANCE_CLAMPED,
        AUDIO_ATTENUATION_MAX = AUDIO_ATTENUATION_EXPONENT_DISTANCE_CLAMPED
    };
}
